version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"

  frappe:
    build: .
    ports:
     - "8000:5000"
    stdin_open: true
    tty: true
    #links:
    #  - redis
    #  - mariadb
    network_mode: "host"
    depends_on:
      - "mariadb"
      - "redis"
    volumes:
      - ./code:/home/frappe/code

